<a href="https://colab.research.google.com/github/toashishagarwal/LearningPyTorch/blob/main/LayerNormalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import torch.nn as nn

In [17]:
torch.manual_seed(123)
batch_example=torch.randn(2,5)
print(batch_example)


tensor([[-0.1115,  0.1204, -0.3696, -0.2404, -1.1969],
        [ 0.2093, -0.9724, -0.7550,  0.3239, -0.1085]])


In [25]:
layer = nn.Sequential(nn.Linear(5,6), nn.ReLU())
out = layer(batch_example)
print(out)

tensor([[0.6470, 0.6470, 0.0000, 0.3006, 0.0000, 0.0000],
        [0.5093, 0.7736, 0.3180, 0.7429, 0.2218, 0.0000]],
       grad_fn=<ReluBackward0>)


In [26]:
mean = out.mean(dim=-1, keepdim=True)
var = out.var(dim=-1, keepdim=True)
print("Mean:\n", mean)
print("Variance:\n", var)

Mean:
 tensor([[0.2658],
        [0.4276]], grad_fn=<MeanBackward1>)
Variance:
 tensor([[0.1008],
        [0.0926]], grad_fn=<VarBackward0>)


In [27]:
#  Layer Normalization Step
out_norm = (out - mean) / torch.sqrt(var)
mean = out_norm.mean(dim=-1, keepdim=True)
var = out_norm.var(dim=-1, keepdim=True)
print("Normalized layer outputs:\n", out_norm)
print("Mean:\n", mean)
print("Variance:\n", var)

Normalized layer outputs:
 tensor([[ 1.2010,  1.2011, -0.8372,  0.1096, -0.8372, -0.8372],
        [ 0.2684,  1.1371, -0.3603,  1.0362, -0.6763, -1.4050]],
       grad_fn=<DivBackward0>)
Mean:
 tensor([[3.3528e-08],
        [5.9605e-08]], grad_fn=<MeanBackward1>)
Variance:
 tensor([[1.0000],
        [1.0000]], grad_fn=<VarBackward0>)


The answer above is presented in scientific notation (note the 'e' in the tensor outputs). This makes reading hard. To improve readability, we can also turn off the scientific notation when printing
tensor values by setting sci_mode to False:

In [28]:
torch.set_printoptions(sci_mode=False)
print("Mean:\n", mean)
print("Variance:\n", var)

Mean:
 tensor([[    0.0000],
        [    0.0000]], grad_fn=<MeanBackward1>)
Variance:
 tensor([[1.0000],
        [1.0000]], grad_fn=<VarBackward0>)
